from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='DoctorProfile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('specialization', models.CharField(max_length=120)), ('room', models.CharField(max_length=80)), ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy / With Patient'), ('break', 'On Break'), ('unavailable', 'Unavailable')], default='unavailable', max_length=16)), ('status_updated_at', models.DateTimeField(auto_now=True)), ('expected_availability', models.CharField(blank=True, max_length=160)), ('accepting_patients', models.BooleanField(default=True)), ('active', models.BooleanField(default=True)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='PHCSettings', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('opening_hours', models.CharField(default='Monday-Saturday, 9:00 AM-5:00 PM', max_length=255)), ('phc_phone', models.CharField(blank=True, max_length=50)), ('ambulance_phone', models.CharField(blank=True, max_length=50)), ('security_phone', models.CharField(blank=True, max_length=50)), ('emergency_hospital', models.CharField(blank=True, max_length=255))]),
        migrations.CreateModel(name='PHCNotification', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('message', models.CharField(max_length=255)), ('created_at', models.DateTimeField(auto_now_add=True)), ('read_at', models.DateTimeField(blank=True, null=True)), ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phc_notifications', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='PHCAnnouncement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=160)), ('message', models.TextField()), ('created_at', models.DateTimeField(auto_now_add=True)), ('expires_at', models.DateTimeField(blank=True, null=True)), ('active', models.BooleanField(default=True)), ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phc_announcements', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='DoctorSchedule', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('day', models.CharField(choices=[('mon','Monday'),('tue','Tuesday'),('wed','Wednesday'),('thu','Thursday'),('fri','Friday'),('sat','Saturday'),('sun','Sunday')], max_length=3)), ('start_time', models.TimeField()), ('end_time', models.TimeField()), ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='phc.doctorprofile'))], options={'ordering': ['day', 'start_time']}),
        migrations.CreateModel(name='DoctorNotificationSubscription', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('notified_at', models.DateTimeField(blank=True, null=True)), ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='phc.doctorprofile')), ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phc_notification_subscriptions', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ConsultationQueue', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('token_number', models.PositiveIntegerField()), ('status', models.CharField(choices=[('waiting','Waiting'),('called','Called'),('completed','Completed'),('skipped','Skipped'),('cancelled','Cancelled')], default='waiting', max_length=12)), ('joined_at', models.DateTimeField(auto_now_add=True)), ('called_at', models.DateTimeField(blank=True, null=True)), ('completed_at', models.DateTimeField(blank=True, null=True)), ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='phc.doctorprofile')), ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phc_queue_entries', to=settings.AUTH_USER_MODEL))], options={'ordering': ['token_number']}),
        migrations.CreateModel(name='AuditLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('action', models.CharField(max_length=160)), ('relevant_object', models.CharField(blank=True, max_length=255)), ('timestamp', models.DateTimeField(auto_now_add=True)), ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phc_audit_logs', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-timestamp']}),
        migrations.AddConstraint(model_name='doctorschedule', constraint=models.UniqueConstraint(fields=('doctor','day','start_time'), name='unique_doctor_schedule_slot')),
        migrations.AddConstraint(model_name='doctornotificationsubscription', constraint=models.UniqueConstraint(fields=('student','doctor'), name='unique_doctor_notification_subscription')),
        migrations.AddConstraint(model_name='consultationqueue', constraint=models.UniqueConstraint(fields=('doctor','token_number'), name='unique_doctor_token')),
        migrations.AddConstraint(model_name='consultationqueue', constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['waiting','called'])), fields=('student','doctor'), name='unique_active_student_doctor_queue')),
    ]
