# Generated by Django 5.2.16 on 2026-08-04 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('capacity', models.PositiveIntegerField()),
                ('has_projector', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_audio_system', models.BooleanField(default=False)),
                ('has_smart_board', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('CLUB', 'Club Event'), ('EXTRA_CLASS', 'Extra Class'), ('EXAM', 'Exam'), ('MEETING', 'Meeting'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('OTHER', 'Other')], max_length=30)),
                ('purpose', models.TextField()),
                ('expected_strength', models.PositiveIntegerField()),
                ('branches', models.JSONField(default=list)),
                ('years', models.JSONField(default=list)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('require_projector', models.BooleanField(default=False)),
                ('require_ac', models.BooleanField(default=False)),
                ('require_wifi', models.BooleanField(default=False)),
                ('require_audio_system', models.BooleanField(default=False)),
                ('require_smart_board', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('registration_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinators', models.ManyToManyField(blank=True, related_name='coordinated_scheduler_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scheduler_events', to=settings.AUTH_USER_MODEL)),
                ('booked_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_events', to='scheduler.room')),
            ],
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('ROOM_CHANGED', 'Room Changed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('AUTO_ROOM_CHANGED', 'Automatic Room Change')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_booking_changes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to='scheduler.event')),
                ('new_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduler.room')),
                ('old_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduler.room')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('branch', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.room')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='scheduler.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_scheduler_event_registration')],
            },
        ),
    ]
