# Generated by Django 5.2.16 on 2026-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
