# Generated by Codex on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_roombookingpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
