# Generated by Django 5.2.16 on 2026-08-04 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('route', models.CharField(choices=[('college_city', 'College to City'), ('city_college', 'City to College')], max_length=32)),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('departure_time', models.TimeField()),
                ('price', models.PositiveIntegerField(default=100)),
                ('max_capacity', models.PositiveSmallIntegerField(default=40)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day', 'departure_time'],
                'unique_together': {('name', 'day', 'departure_time')},
            },
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('travel_date', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('route', models.CharField(choices=[('college_city', 'College to City'), ('city_college', 'City to College')], max_length=32)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('payment_reference', models.CharField(blank=True, max_length=128)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=128)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bus.busschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-travel_date', '-booked_at'],
            },
        ),
    ]
